# Generated by Django 6.0.3 on 2026-05-08 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('color', models.CharField(default='#4f46e5', help_text='Hex color, e.g. #4f46e5', max_length=7)),
                ('map_x', models.PositiveIntegerField(default=50, help_text='Horizontal position in percent (0-100)')),
                ('map_y', models.PositiveIntegerField(default=50, help_text='Vertical position in percent (0-100)')),
                ('icon', models.CharField(blank=True, help_text='Optional emoji or short icon text', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Project categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='researchproject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory'),
        ),
    ]
