# Generated by Django 6.0.3 on 2026-05-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectcategory_researchproject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='cmu_mis_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='imported_end_date_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='imported_start_date_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='project_code',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
