# Generated by Codex on 2026-05-14

from django.db import migrations


CITY_CATEGORIES = [
    {
        "slug": "smart-agriculture-future-food",
        "name": "Smart Agriculture and Future Food",
        "color": "#4f9f36",
        "icon": "AG",
        "map_x": 18,
        "map_y": 16,
        "display_order": 1,
    },
    {
        "slug": "energy-environment-sustainability",
        "name": "Energy, Environment and Sustainability",
        "color": "#1f5f9f",
        "icon": "EN",
        "map_x": 43,
        "map_y": 15,
        "display_order": 2,
    },
    {
        "slug": "ai-digital-intelligent-technology",
        "name": "AI, Digital and Intelligent Technology",
        "color": "#6d48c7",
        "icon": "AI",
        "map_x": 66,
        "map_y": 16,
        "display_order": 3,
    },
    {
        "slug": "economy-finance-forecasting",
        "name": "Economy, Finance and Forecasting",
        "color": "#be7b1b",
        "icon": "EC",
        "map_x": 85,
        "map_y": 26,
        "display_order": 4,
    },
    {
        "slug": "health-society-wellbeing",
        "name": "Health, Society and Wellbeing",
        "color": "#c04f67",
        "icon": "HL",
        "map_x": 14,
        "map_y": 52,
        "display_order": 5,
    },
    {
        "slug": "water-regional-environment-management",
        "name": "Water and Regional Environment Management",
        "color": "#4aa7b3",
        "icon": "WT",
        "map_x": 88,
        "map_y": 50,
        "display_order": 6,
    },
    {
        "slug": "policy-science-institutional-development",
        "name": "Policy, Science and Institutional Development",
        "color": "#2d66a9",
        "icon": "PL",
        "map_x": 16,
        "map_y": 75,
        "display_order": 7,
    },
    {
        "slug": "community-economy-high-value-supply-chain",
        "name": "Community Economy and High-Value Supply Chain",
        "color": "#c5932f",
        "icon": "CM",
        "map_x": 40,
        "map_y": 74,
        "display_order": 8,
    },
    {
        "slug": "impact-assessment-public-policy",
        "name": "Impact Assessment and Public Policy",
        "color": "#4b5f78",
        "icon": "IA",
        "map_x": 58,
        "map_y": 84,
        "display_order": 9,
    },
    {
        "slug": "data-infrastructure-smart-city",
        "name": "Data Infrastructure and Smart City",
        "color": "#5b9a3b",
        "icon": "DT",
        "map_x": 82,
        "map_y": 83,
        "display_order": 10,
    },
]


def seed_city_categories(apps, schema_editor):
    ProjectCategory = apps.get_model("projects", "ProjectCategory")
    for item in CITY_CATEGORIES:
        defaults = {
            "name": item["name"],
            "color": item["color"],
            "icon": item["icon"],
            "map_x": item["map_x"],
            "map_y": item["map_y"],
            "display_order": item["display_order"],
            "description": f"Category for {item['name']}.",
            "is_active": True,
        }
        ProjectCategory.objects.update_or_create(slug=item["slug"], defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_researchproject_cmu_mis_code_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_city_categories, migrations.RunPython.noop),
    ]
