# Generated by Django 6.0.3 on 2026-04-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField(blank=True)),
                ('authors', models.CharField(max_length=255)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='publications/')),
                ('external_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
