# Generated by Django 6.0.3 on 2026-04-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='citescore',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='citescore_percentile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='eissn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='publication',
            name='impact_factor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='impact_factor_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publication',
            name='issn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_quartile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_quartile_basis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publication',
            name='scopus_eid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='scopus_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='publication',
            name='scopus_source_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='publication',
            name='sjr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='snip',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='source',
            field=models.CharField(default='manual', max_length=50),
        ),
    ]
