# Generated by Django 6.0.3 on 2026-04-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_citescore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='all_authors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='corresponding_author',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
