# Generated by Django 6.0.3 on 2026-04-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_all_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='sdg_goals',
            field=models.CharField(blank=True, help_text='Comma-separated SDG numbers, e.g. 3,4,9,13', max_length=120),
        ),
    ]
