# Generated by Django 6.0.3 on 2026-04-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='scopus_author_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
