# Generated by Django 6.0.3 on 2026-04-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0002_researcher_scopus_author_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researcher',
            options={'ordering': ['display_order', 'full_name']},
        ),
        migrations.AddField(
            model_name='researcher',
            name='academic_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='researcher',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researcher',
            name='organization_role',
            field=models.CharField(choices=[('director', 'Director'), ('deputy_director', 'Deputy Director'), ('secretary', 'Secretary'), ('team_lead', 'Team Lead'), ('researcher', 'Researcher'), ('part_time_researcher', 'Part-time Researcher')], default='researcher', max_length=30),
        ),
        migrations.AddField(
            model_name='researcher',
            name='team_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
